export const Category = {
  0: 'Standard Note',
  1: 'Letter Produced',
  2: 'Email Sent',
  3: 'Email Saved',
  4: 'Report Exported',
  5: 'Mail Merge',
  7: 'Fact-find - Dependants',
  8: 'Fact-find - Incomes',
  9: 'Fact-find - Outgoings',
  10: 'Fact-find - Employments',
  11: 'Fact-find - Assets',
  12: 'Fact-find - Liabilities',
  13: 'Fact-find - Policies',
  14: 'Fact-find - Attitude to Risk',
  15: 'Fact-find - Objectives',
  16: 'Fact-find - Summary',
  18: 'Fact-find - Pensions',
  19: 'Fact-find - Investments',
  20: 'Fact-find - Protection',
  21: 'Fact-find - Mortgages',
  22: 'Document Uploaded',
  23: 'Document Downloaded',
};
